---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: version
  - get: git-repo
    trigger: true
  - put: docker-image
    params:
      build: git-repo
      tag_file: version/number

- name: update-deployment
  plan:
  - get: git-repo
    trigger: true
    passed:
      - build-docker-image
  - put: kubectl
    params:
      file: "git-repo/k8s/deploy.yaml"

resource_types:
- name: concourse-kubectl-resource-type
  type: docker-image
  source: 
    repository: jmkarthik/concourse-kubectl-resource
    tag: latest

resources:
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.tools.sap/I500506/innoweek-ops-bot.git
    branch: version
    file: version
    private_key: null
    skip_ssl_verification: true
    password: ((credentials.landscape_git_password))
    username: ((credentials.landscape_git_user))

- name: git-repo
  type: git
  source:
    uri: https://github.tools.sap/I500506/innoweek-ops-bot.git
    branch: master
    private_key: null
    skip_ssl_verification: true
    password: ((credentials.landscape_git_password))
    username: ((credentials.landscape_git_user))

- name: docker-image
  type: docker-image
  source:
    email: ((credentials.docker_email))
    username: ((credentials.docker_user))
    password: ((credentials.docker_password))
    repository: anaikdocker/slackbot

- name: kubectl
  type: concourse-kubectl-resource-type
  source:
    api_server_uri: ((credentials.kube_api_server_uri))
    namespace: default
    certificate_authority_data: ((credentials.kube_certificate_authority_data))
    token: ((credentials.kube_api_token))