apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-bot-env-file
data:
  SLACK_SIGNING_SECRET: 28216d57f4c625ef30917052cb8350c9
  SLACK_BOT_TOKEN: xoxb-468539598229-1611298894758-PFStcqsoVdHOpxK9kELYmdbX

---
apiVersion: v1
kind: Service
metadata:
  name: python-slack-bot-svc
spec:
  selector:
    app: python-slack-bot
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-slack-bot-app
spec:
  selector:
    matchLabels:
      app: python-slack-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: python-slack-bot
    spec:
      containers:
      - name: python-slack-bot
        image: anaikdocker/slackbot:v4
        ports:
        - containerPort: 5000
        env:
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            configMapKeyRef:
              name: slack-bot-env-file
              key: SLACK_SIGNING_SECRET
        - name: SLACK_BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: slack-bot-env-file
              key: SLACK_BOT_TOKEN