apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: kube_api_server_uri
  name: k8scluster
contexts:
- context:
    cluster: k8scluster
    namespace: garden-dtslrt
    user: k8suser
  name: k8scontext
current-context: k8scontext
kind: Config
users:
- name: k8suser
  user:
    token: kube_api_token